# Generated by Django 3.2.7 on 2022-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaMahasiswa',
            fields=[
                ('noanggotam', models.CharField(db_column='NoAnggotaM', max_length=20, primary_key=True, serialize=False)),
                ('nim', models.CharField(db_column='NIM', max_length=15)),
                ('namaanggota', models.CharField(db_column='NamaAnggota', max_length=50)),
                ('jurusan', models.CharField(db_column='Jurusan', max_length=20)),
                ('tanggallahir', models.DateField(db_column='TanggalLahir')),
                ('alamat', models.CharField(db_column='Alamat', max_length=50)),
                ('kodepos', models.CharField(db_column='KodePos', max_length=20)),
                ('notelp', models.CharField(blank=True, db_column='NoTelp', max_length=20, null=True)),
                ('hp', models.CharField(blank=True, db_column='HP', max_length=20, null=True)),
                ('angkatan', models.IntegerField(db_column='Angkatan')),
                ('namaortu', models.CharField(db_column='NamaOrtu', max_length=50)),
                ('alamatortu', models.CharField(db_column='AlamatOrtu', max_length=50)),
                ('notelportu', models.CharField(blank=True, db_column='NoTelpOrtu', max_length=20, null=True)),
                ('jeniskelamin', models.CharField(db_column='JenisKelamin', max_length=20)),
                ('tempatlahir', models.CharField(db_column='TempatLahir', max_length=20)),
                ('poto', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
            ],
            options={
                'db_table': 'anggota_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnggotaNonMahasiswa',
            fields=[
                ('noanggotan', models.CharField(db_column='NoAnggotaN', max_length=10, primary_key=True, serialize=False)),
                ('nip', models.CharField(db_column='NIP', max_length=15)),
                ('namaanggota', models.CharField(db_column='NamaAnggota', max_length=50)),
                ('jabatan', models.CharField(db_column='Jabatan', max_length=20)),
                ('tanggallahir', models.DateField(db_column='TanggalLahir')),
                ('alamat', models.CharField(db_column='Alamat', max_length=50)),
                ('kodepos', models.CharField(db_column='KodePos', max_length=20)),
                ('notelp', models.CharField(db_column='NoTelp', max_length=20)),
                ('hp', models.CharField(blank=True, db_column='HP', max_length=20, null=True)),
                ('tgldaftar', models.CharField(db_column='TglDaftar', max_length=5)),
                ('jeniskelamin', models.CharField(db_column='JenisKelamin', max_length=20)),
                ('tempatlahir', models.CharField(db_column='TempatLahir', max_length=20)),
                ('poto', models.FileField(blank=True, max_length=255, null=True, upload_to='myapp/static/myapp/upload/')),
            ],
            options={
                'db_table': 'anggota_non_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('kodebuku', models.CharField(db_column='KodeBuku', max_length=10, primary_key=True, serialize=False)),
                ('noudc', models.CharField(blank=True, db_column='NoUDC', max_length=20, null=True)),
                ('noreg', models.CharField(blank=True, db_column='NoReg', max_length=20, null=True)),
                ('judul', models.CharField(db_column='Judul', max_length=50)),
                ('penerbit', models.CharField(db_column='Penerbit', max_length=50)),
                ('pengarang', models.CharField(db_column='Pengarang', max_length=50)),
                ('thnterbit', models.CharField(db_column='ThnTerbit', max_length=5)),
                ('kotaterbit', models.CharField(db_column='KotaTerbit', max_length=20)),
                ('bahasa', models.CharField(db_column='Bahasa', max_length=20)),
                ('edisi', models.CharField(db_column='Edisi', max_length=20)),
                ('deskripsi', models.CharField(blank=True, db_column='Deskripsi', max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, db_column='Isbn', max_length=20, null=True)),
                ('jumekslempar', models.IntegerField(blank=True, db_column='JumEkslempar', null=True)),
                ('subyekutama', models.CharField(blank=True, db_column='SubyekUtama', max_length=50, null=True)),
                ('subyektambahan', models.CharField(blank=True, db_column='SubyekTambahan', max_length=50, null=True)),
                ('sampul', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
            ],
            options={
                'db_table': 'buku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KembaliMahasiswa',
            fields=[
                ('nokembalim', models.CharField(db_column='NoKembaliM', max_length=10, primary_key=True, serialize=False)),
                ('tglkembali', models.DateField(db_column='TglKembali')),
                ('kodepetugas', models.CharField(db_column='KodePetugas', max_length=10)),
                ('denda', models.CharField(db_column='Denda', max_length=255)),
            ],
            options={
                'db_table': 'kembali_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KembaliNonMahasiswa',
            fields=[
                ('nokembalin', models.CharField(db_column='NoKembaliN', max_length=10, primary_key=True, serialize=False)),
                ('tglkembali', models.DateField(db_column='TglKembali')),
                ('kodepetugas', models.CharField(db_column='KodePetugas', max_length=10)),
                ('denda', models.CharField(db_column='Denda', max_length=255)),
            ],
            options={
                'db_table': 'kembali_non_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('kodepetugas', models.CharField(db_column='KodePetugas', max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(db_column='Nama', max_length=50)),
                ('jabatan', models.CharField(db_column='Jabatan', max_length=20)),
                ('hakakses', models.CharField(db_column='HakAkses', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'petugas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamDetailMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(db_column='Judul', max_length=50)),
                ('penerbit', models.CharField(db_column='Penerbit', max_length=50)),
                ('thnterbit', models.CharField(db_column='ThnTerbit', max_length=5)),
                ('jml', models.IntegerField(db_column='Jml')),
            ],
            options={
                'db_table': 'pinjam_detail_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamDetailNonMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, db_column='Judul', max_length=50, null=True)),
                ('penerbit', models.CharField(blank=True, db_column='Penerbit', max_length=50, null=True)),
                ('thnterbit', models.CharField(blank=True, db_column='ThnTerbit', max_length=5, null=True)),
                ('jml', models.IntegerField(blank=True, db_column='Jml', null=True)),
            ],
            options={
                'db_table': 'pinjam_detail_non_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamHeaderMahasiswa',
            fields=[
                ('nopinjamm', models.CharField(db_column='NopinjamM', max_length=10, primary_key=True, serialize=False)),
                ('tglpinjam', models.DateField(db_column='TglPinjam')),
                ('tglkembali', models.DateField(db_column='TglKembali')),
            ],
            options={
                'db_table': 'pinjam_header_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamHeaderNonMahasiswa',
            fields=[
                ('nopinjamn', models.CharField(db_column='NopinjamN', max_length=10, primary_key=True, serialize=False)),
                ('tglpinjam', models.DateField(db_column='TglPinjam')),
                ('tglkembali', models.DateField(db_column='TglKembali')),
            ],
            options={
                'db_table': 'pinjam_header_non_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nopinjamm', models.CharField(db_column='NoPinjamM', max_length=10)),
                ('kodebuku', models.CharField(db_column='KodeBuku', max_length=10)),
                ('judul', models.CharField(db_column='Judul', max_length=50)),
                ('penerbit', models.CharField(db_column='Penerbit', max_length=50)),
                ('thnterbit', models.CharField(db_column='ThnTerbit', max_length=5)),
                ('jml', models.IntegerField(db_column='Jml')),
                ('noanggotam', models.CharField(db_column='NoAnggotaM', max_length=10)),
                ('tglpinjam', models.DateField(db_column='TglPinjam')),
                ('tglkembali', models.DateField(db_column='TglKembali')),
            ],
            options={
                'db_table': 'pinjam_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamNonMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nopinjamn', models.CharField(db_column='NoPinjamN', max_length=10)),
                ('kodebuku', models.CharField(db_column='KodeBuku', max_length=10)),
                ('judul', models.CharField(db_column='Judul', max_length=50)),
                ('penerbit', models.CharField(db_column='Penerbit', max_length=50)),
                ('thnterbit', models.CharField(db_column='ThnTerbit', max_length=5)),
                ('jml', models.IntegerField(db_column='Jml')),
                ('noanggotan', models.CharField(db_column='NoAnggotaN', max_length=10)),
                ('tglpinjam', models.DateField(db_column='TglPinjam')),
                ('tglkembali', models.DateField(db_column='TglKembali')),
            ],
            options={
                'db_table': 'pinjam_non_mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
    ]
