# Generated by Django 4.0.5 on 2022-06-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('gambar', models.FileField(upload_to='myapp/static/myapp/upload/')),
            ],
        ),
    ]
